# Site settings
title: Stuff to do in Houston

description: > # A site of things to do in Houston for when people visit for conferences etc.
baseurl: ""
url: "http://stuffinhouston.com"
development: false

google_analytics: ""

map_options:
  lat: 29.7625152
  lng: -95.5070497
  zoom: 11
  api_key: "AIzaSyBMOYl6iMtpsaoFE3y--1s_LccxtT5FMlM"

collections:
  restaurants:
    output: true
    permalink: /restaurant/:path/
  activities:
    output: true
    permalink: /activty/:path/
  places:
    output: true
    permalink: /places/:path/


# Build settings
markdown: kramdown

exclude:
  - CONTRIBUTING.md
  - README.md
  - config.rb
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - lint.yml
